version: '3'

services:
  
  ethminer:
    container_name: ethminer
    image: ethminer:0.18.0
    build: 
      context: .
      args:
        binary_file: ethminer-0.18.0-cuda-8-linux-x86_64.tar.gz
        pool_url: TBD
    restart: unless-stopped
